### PR TITLE
Feat/grade pages

### PR DESCRIPTION
**Pull request by sairaheta1**
The only portion of the page I wasn't able to create was replacing the bullet points with the specific book icon we wanted. I still experimented how to change the bullets, but I didn't want to use my personal Font Awesome token URL for the client project.

### CODE REVIEW

**Review by Austin2Shih — CHANGES_REQUESTED** [review]
Overall, the code looks great! There are some minor styling things that are missing but I think we can still just merge to main and change those in the future. I requested one change that involved the map function but it's super minor and kind of just gets rid of a warning.

**Comment by sairaheta1** [comment]
Just fixed it!

**Comment by sairaheta1** [comment]
I was able to finish the desktop version for these pages.

**Review by yugii28 — APPROVED** [review]
The code for both the mobile and desktop version looks perfect, we'll merge this into main immediately. Thank you for finishing the desktop version and adding responsiveness super quickly, we really appreciate it!

**Pull request merged**
